export enum TalentPermission {
  CANDIDATE_READ_PUBLIC = 'candidate.read_public',
  CANDIDATE_READ_PRIVATE = 'candidate.read_private',
  CANDIDATE_WRITE_SELF = 'candidate.write_self',
  EMPLOYER_SEARCH = 'employer.search',
  EMPLOYER_REQUEST_INTRO = 'employer.request_intro',
  EMPLOYER_DOWNLOAD_CV = 'employer.download_cv',
  EMPLOYER_POST_JOB = 'employer.post_job',
  EMPLOYER_MANAGE_ORG = 'employer.manage_org',
  PLACEMENT_APPROVE_PROFILE = 'placement.approve_profile',
  PLACEMENT_MANAGE_EMPLOYERS = 'placement.manage_employers',
  PLACEMENT_MODERATE_JOBS = 'placement.moderate_jobs',
  PLACEMENT_MANAGE_INTROS = 'placement.manage_intros',
  PLACEMENT_UPDATE_STATUS = 'placement.update_status',
  PLACEMENT_EXPORT_REPORTS = 'placement.export_reports',
  PLACEMENT_VIEW_REPORTS = 'placement.view_reports',
  PLACEMENT_BULK_IMPORT = 'placement.bulk_import',
  ADMIN_MANAGE_ROLES = 'admin.manage_roles',
  ADMIN_MANAGE_TAXONOMY = 'admin.manage_taxonomy',
  ADMIN_VIEW_AUDIT_LOGS = 'admin.view_audit_logs',
  ADMIN_MANAGE_SETTINGS = 'admin.manage_settings',
  EMPLOYER_MANAGE_PIPELINE = 'employer.manage_pipeline',
  EMPLOYER_SCHEDULE_INTERVIEW = 'employer.schedule_interview',
  EMPLOYER_VIEW_ANALYTICS = 'employer.view_analytics',
  EMPLOYER_MANAGE_TEAM = 'employer.manage_team',
}

export const ROLE_PERMISSIONS: Record<string, TalentPermission[]> = {
  candidate: [
    TalentPermission.CANDIDATE_READ_PUBLIC,
    TalentPermission.CANDIDATE_WRITE_SELF,
  ],
  employer_member: [
    TalentPermission.CANDIDATE_READ_PUBLIC,
    TalentPermission.EMPLOYER_SEARCH,
    TalentPermission.EMPLOYER_MANAGE_PIPELINE,
    TalentPermission.EMPLOYER_SCHEDULE_INTERVIEW,
    TalentPermission.EMPLOYER_VIEW_ANALYTICS,
  ],
  employer_admin: [
    TalentPermission.CANDIDATE_READ_PUBLIC,
    TalentPermission.CANDIDATE_READ_PRIVATE,
    TalentPermission.EMPLOYER_SEARCH,
    TalentPermission.EMPLOYER_REQUEST_INTRO,
    TalentPermission.EMPLOYER_DOWNLOAD_CV,
    TalentPermission.EMPLOYER_POST_JOB,
    TalentPermission.EMPLOYER_MANAGE_ORG,
    TalentPermission.EMPLOYER_MANAGE_PIPELINE,
    TalentPermission.EMPLOYER_SCHEDULE_INTERVIEW,
    TalentPermission.EMPLOYER_VIEW_ANALYTICS,
    TalentPermission.EMPLOYER_MANAGE_TEAM,
  ],
  placement_officer: [
    TalentPermission.CANDIDATE_READ_PUBLIC,
    TalentPermission.CANDIDATE_READ_PRIVATE,
    TalentPermission.EMPLOYER_SEARCH,
    TalentPermission.PLACEMENT_APPROVE_PROFILE,
    TalentPermission.PLACEMENT_MANAGE_EMPLOYERS,
    TalentPermission.PLACEMENT_MODERATE_JOBS,
    TalentPermission.PLACEMENT_MANAGE_INTROS,
    TalentPermission.PLACEMENT_UPDATE_STATUS,
    TalentPermission.PLACEMENT_VIEW_REPORTS,
  ],
  placement_manager: [
    TalentPermission.CANDIDATE_READ_PUBLIC,
    TalentPermission.CANDIDATE_READ_PRIVATE,
    TalentPermission.EMPLOYER_SEARCH,
    TalentPermission.PLACEMENT_APPROVE_PROFILE,
    TalentPermission.PLACEMENT_MANAGE_EMPLOYERS,
    TalentPermission.PLACEMENT_MODERATE_JOBS,
    TalentPermission.PLACEMENT_MANAGE_INTROS,
    TalentPermission.PLACEMENT_UPDATE_STATUS,
    TalentPermission.PLACEMENT_VIEW_REPORTS,
    TalentPermission.PLACEMENT_EXPORT_REPORTS,
    TalentPermission.PLACEMENT_BULK_IMPORT,
    TalentPermission.ADMIN_MANAGE_ROLES,
    TalentPermission.ADMIN_MANAGE_TAXONOMY,
    TalentPermission.ADMIN_VIEW_AUDIT_LOGS,
  ],
  super_admin: Object.values(TalentPermission),
};
