package itsm

import (
	"context"
	"encoding/json"
	"log/slog"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/itd-cbn/itd-opms-api/internal/platform/audit"
	apperrors "github.com/itd-cbn/itd-opms-api/internal/shared/errors"
	"github.com/itd-cbn/itd-opms-api/internal/shared/types"
)

// ──────────────────────────────────────────────
// ProblemService
// ──────────────────────────────────────────────

// ProblemService handles business logic for problem management and known errors.
type ProblemService struct {
	pool     *pgxpool.Pool
	auditSvc *audit.AuditService
}

// NewProblemService creates a new ProblemService.
func NewProblemService(pool *pgxpool.Pool, auditSvc *audit.AuditService) *ProblemService {
	return &ProblemService{
		pool:     pool,
		auditSvc: auditSvc,
	}
}

// ──────────────────────────────────────────────
// Problems
// ──────────────────────────────────────────────

// CreateProblem creates a new problem record. The problem_number is auto-generated by a DB trigger.
func (s *ProblemService) CreateProblem(ctx context.Context, req CreateProblemRequest) (Problem, error) {
	auth := types.GetAuthContext(ctx)
	if auth == nil {
		return Problem{}, apperrors.Unauthorized("authentication required")
	}

	id := uuid.New()
	now := time.Now().UTC()

	query := `
		INSERT INTO problems (
			id, tenant_id, title, description,
			status, owner_id, created_at, updated_at
		) VALUES (
			$1, $2, $3, $4,
			$5, $6, $7, $8
		)
		RETURNING id, tenant_id, problem_number, title, description,
			root_cause, status, linked_incident_ids, workaround,
			permanent_fix, linked_change_id, owner_id,
			created_at, updated_at`

	status := req.Status
	if status == "" {
		status = "logged"
	}

	var p Problem
	err := s.pool.QueryRow(ctx, query,
		id, auth.TenantID, req.Title, req.Description,
		status, req.OwnerID, now, now,
	).Scan(
		&p.ID, &p.TenantID, &p.ProblemNumber, &p.Title, &p.Description,
		&p.RootCause, &p.Status, &p.LinkedIncidentIDs, &p.Workaround,
		&p.PermanentFix, &p.LinkedChangeID, &p.OwnerID,
		&p.CreatedAt, &p.UpdatedAt,
	)
	if err != nil {
		return Problem{}, apperrors.Internal("failed to create problem", err)
	}

	// Log audit event.
	changes, _ := json.Marshal(map[string]any{
		"title":  req.Title,
		"status": "open",
	})
	if auditErr := s.auditSvc.Log(ctx, audit.AuditEntry{
		TenantID:   auth.TenantID,
		ActorID:    auth.UserID,
		Action:     "create:problem",
		EntityType: "problem",
		EntityID:   id,
		Changes:    changes,
	}); auditErr != nil {
		slog.ErrorContext(ctx, "failed to log audit event", "error", auditErr)
	}

	return p, nil
}

// GetProblem retrieves a single problem by ID.
func (s *ProblemService) GetProblem(ctx context.Context, id uuid.UUID) (Problem, error) {
	auth := types.GetAuthContext(ctx)
	if auth == nil {
		return Problem{}, apperrors.Unauthorized("authentication required")
	}

	query := `
		SELECT id, tenant_id, problem_number, title, description,
			root_cause, status, linked_incident_ids, workaround,
			permanent_fix, linked_change_id, owner_id,
			created_at, updated_at
		FROM problems
		WHERE id = $1 AND tenant_id = $2`

	var p Problem
	err := s.pool.QueryRow(ctx, query, id, auth.TenantID).Scan(
		&p.ID, &p.TenantID, &p.ProblemNumber, &p.Title, &p.Description,
		&p.RootCause, &p.Status, &p.LinkedIncidentIDs, &p.Workaround,
		&p.PermanentFix, &p.LinkedChangeID, &p.OwnerID,
		&p.CreatedAt, &p.UpdatedAt,
	)
	if err != nil {
		if err == pgx.ErrNoRows {
			return Problem{}, apperrors.NotFound("Problem", id.String())
		}
		return Problem{}, apperrors.Internal("failed to get problem", err)
	}

	return p, nil
}

// ListProblems returns a filtered, paginated list of problems.
func (s *ProblemService) ListProblems(ctx context.Context, status *string, limit, offset int) ([]Problem, int64, error) {
	auth := types.GetAuthContext(ctx)
	if auth == nil {
		return nil, 0, apperrors.Unauthorized("authentication required")
	}

	// Count total matching records.
	countQuery := `
		SELECT COUNT(*)
		FROM problems
		WHERE tenant_id = $1
			AND ($2::text IS NULL OR status = $2)`

	var total int64
	err := s.pool.QueryRow(ctx, countQuery, auth.TenantID, status).Scan(&total)
	if err != nil {
		return nil, 0, apperrors.Internal("failed to count problems", err)
	}

	// Fetch paginated results.
	dataQuery := `
		SELECT id, tenant_id, problem_number, title, description,
			root_cause, status, linked_incident_ids, workaround,
			permanent_fix, linked_change_id, owner_id,
			created_at, updated_at
		FROM problems
		WHERE tenant_id = $1
			AND ($2::text IS NULL OR status = $2)
		ORDER BY created_at DESC
		LIMIT $3 OFFSET $4`

	rows, err := s.pool.Query(ctx, dataQuery, auth.TenantID, status, limit, offset)
	if err != nil {
		return nil, 0, apperrors.Internal("failed to list problems", err)
	}
	defer rows.Close()

	var problems []Problem
	for rows.Next() {
		var p Problem
		if err := rows.Scan(
			&p.ID, &p.TenantID, &p.ProblemNumber, &p.Title, &p.Description,
			&p.RootCause, &p.Status, &p.LinkedIncidentIDs, &p.Workaround,
			&p.PermanentFix, &p.LinkedChangeID, &p.OwnerID,
			&p.CreatedAt, &p.UpdatedAt,
		); err != nil {
			return nil, 0, apperrors.Internal("failed to scan problem", err)
		}
		problems = append(problems, p)
	}

	if err := rows.Err(); err != nil {
		return nil, 0, apperrors.Internal("failed to iterate problems", err)
	}

	if problems == nil {
		problems = []Problem{}
	}

	return problems, total, nil
}

// UpdateProblem updates an existing problem using COALESCE partial update.
func (s *ProblemService) UpdateProblem(ctx context.Context, id uuid.UUID, req UpdateProblemRequest) (Problem, error) {
	auth := types.GetAuthContext(ctx)
	if auth == nil {
		return Problem{}, apperrors.Unauthorized("authentication required")
	}

	// Verify the problem exists and belongs to the tenant.
	_, err := s.GetProblem(ctx, id)
	if err != nil {
		return Problem{}, err
	}

	now := time.Now().UTC()

	updateQuery := `
		UPDATE problems SET
			title = COALESCE($1, title),
			description = COALESCE($2, description),
			root_cause = COALESCE($3, root_cause),
			status = COALESCE($4, status),
			workaround = COALESCE($5, workaround),
			permanent_fix = COALESCE($6, permanent_fix),
			linked_change_id = COALESCE($7, linked_change_id),
			owner_id = COALESCE($8, owner_id),
			updated_at = $9
		WHERE id = $10 AND tenant_id = $11
		RETURNING id, tenant_id, problem_number, title, description,
			root_cause, status, linked_incident_ids, workaround,
			permanent_fix, linked_change_id, owner_id,
			created_at, updated_at`

	var p Problem
	err = s.pool.QueryRow(ctx, updateQuery,
		req.Title, req.Description, req.RootCause,
		req.Status, req.Workaround, req.PermanentFix,
		req.LinkedChangeID, req.OwnerID,
		now, id, auth.TenantID,
	).Scan(
		&p.ID, &p.TenantID, &p.ProblemNumber, &p.Title, &p.Description,
		&p.RootCause, &p.Status, &p.LinkedIncidentIDs, &p.Workaround,
		&p.PermanentFix, &p.LinkedChangeID, &p.OwnerID,
		&p.CreatedAt, &p.UpdatedAt,
	)
	if err != nil {
		return Problem{}, apperrors.Internal("failed to update problem", err)
	}

	// Log audit event.
	changes, _ := json.Marshal(req)
	if auditErr := s.auditSvc.Log(ctx, audit.AuditEntry{
		TenantID:   auth.TenantID,
		ActorID:    auth.UserID,
		Action:     "update:problem",
		EntityType: "problem",
		EntityID:   id,
		Changes:    changes,
	}); auditErr != nil {
		slog.ErrorContext(ctx, "failed to log audit event", "error", auditErr)
	}

	return p, nil
}

// DeleteProblem deletes a problem by ID.
func (s *ProblemService) DeleteProblem(ctx context.Context, id uuid.UUID) error {
	auth := types.GetAuthContext(ctx)
	if auth == nil {
		return apperrors.Unauthorized("authentication required")
	}

	query := `DELETE FROM problems WHERE id = $1 AND tenant_id = $2`

	result, err := s.pool.Exec(ctx, query, id, auth.TenantID)
	if err != nil {
		return apperrors.Internal("failed to delete problem", err)
	}

	if result.RowsAffected() == 0 {
		return apperrors.NotFound("Problem", id.String())
	}

	// Log audit event.
	if auditErr := s.auditSvc.Log(ctx, audit.AuditEntry{
		TenantID:   auth.TenantID,
		ActorID:    auth.UserID,
		Action:     "delete:problem",
		EntityType: "problem",
		EntityID:   id,
	}); auditErr != nil {
		slog.ErrorContext(ctx, "failed to log audit event", "error", auditErr)
	}

	return nil
}

// LinkIncident appends an incident ID to the problem's linked_incident_ids array.
func (s *ProblemService) LinkIncident(ctx context.Context, problemID, incidentID uuid.UUID) error {
	auth := types.GetAuthContext(ctx)
	if auth == nil {
		return apperrors.Unauthorized("authentication required")
	}

	query := `
		UPDATE problems SET
			linked_incident_ids = array_append(linked_incident_ids, $1),
			updated_at = $2
		WHERE id = $3 AND tenant_id = $4`

	now := time.Now().UTC()
	result, err := s.pool.Exec(ctx, query, incidentID, now, problemID, auth.TenantID)
	if err != nil {
		return apperrors.Internal("failed to link incident to problem", err)
	}

	if result.RowsAffected() == 0 {
		return apperrors.NotFound("Problem", problemID.String())
	}

	// Log audit event.
	changes, _ := json.Marshal(map[string]any{
		"linked_incident_id": incidentID,
	})
	if auditErr := s.auditSvc.Log(ctx, audit.AuditEntry{
		TenantID:   auth.TenantID,
		ActorID:    auth.UserID,
		Action:     "link_incident:problem",
		EntityType: "problem",
		EntityID:   problemID,
		Changes:    changes,
	}); auditErr != nil {
		slog.ErrorContext(ctx, "failed to log audit event", "error", auditErr)
	}

	return nil
}

// ──────────────────────────────────────────────
// Known Errors
// ──────────────────────────────────────────────

// CreateKnownError creates a new known error record linked to a problem.
func (s *ProblemService) CreateKnownError(ctx context.Context, req CreateKnownErrorRequest) (KnownError, error) {
	auth := types.GetAuthContext(ctx)
	if auth == nil {
		return KnownError{}, apperrors.Unauthorized("authentication required")
	}

	id := uuid.New()
	now := time.Now().UTC()

	query := `
		INSERT INTO known_errors (
			id, problem_id, title, description,
			workaround, kb_article_id, status,
			created_at, updated_at
		) VALUES (
			$1, $2, $3, $4,
			$5, $6, 'active',
			$7, $8
		)
		RETURNING id, problem_id, title, description,
			workaround, kb_article_id, status,
			created_at, updated_at`

	var ke KnownError
	err := s.pool.QueryRow(ctx, query,
		id, req.ProblemID, req.Title, req.Description,
		req.Workaround, req.KBArticleID,
		now, now,
	).Scan(
		&ke.ID, &ke.ProblemID, &ke.Title, &ke.Description,
		&ke.Workaround, &ke.KBArticleID, &ke.Status,
		&ke.CreatedAt, &ke.UpdatedAt,
	)
	if err != nil {
		return KnownError{}, apperrors.Internal("failed to create known error", err)
	}

	// Log audit event.
	changes, _ := json.Marshal(map[string]any{
		"title":      req.Title,
		"problem_id": req.ProblemID,
	})
	if auditErr := s.auditSvc.Log(ctx, audit.AuditEntry{
		TenantID:   auth.TenantID,
		ActorID:    auth.UserID,
		Action:     "create:known_error",
		EntityType: "known_error",
		EntityID:   id,
		Changes:    changes,
	}); auditErr != nil {
		slog.ErrorContext(ctx, "failed to log audit event", "error", auditErr)
	}

	return ke, nil
}

// GetKnownError retrieves a single known error by ID.
func (s *ProblemService) GetKnownError(ctx context.Context, id uuid.UUID) (KnownError, error) {
	auth := types.GetAuthContext(ctx)
	if auth == nil {
		return KnownError{}, apperrors.Unauthorized("authentication required")
	}

	query := `
		SELECT ke.id, ke.problem_id, ke.title, ke.description,
			ke.workaround, ke.kb_article_id, ke.status,
			ke.created_at, ke.updated_at
		FROM known_errors ke
		JOIN problems p ON p.id = ke.problem_id
		WHERE ke.id = $1 AND p.tenant_id = $2`

	var ke KnownError
	err := s.pool.QueryRow(ctx, query, id, auth.TenantID).Scan(
		&ke.ID, &ke.ProblemID, &ke.Title, &ke.Description,
		&ke.Workaround, &ke.KBArticleID, &ke.Status,
		&ke.CreatedAt, &ke.UpdatedAt,
	)
	if err != nil {
		if err == pgx.ErrNoRows {
			return KnownError{}, apperrors.NotFound("KnownError", id.String())
		}
		return KnownError{}, apperrors.Internal("failed to get known error", err)
	}

	return ke, nil
}

// ListKnownErrors returns all known errors for a given problem.
func (s *ProblemService) ListKnownErrors(ctx context.Context, problemID uuid.UUID) ([]KnownError, error) {
	auth := types.GetAuthContext(ctx)
	if auth == nil {
		return nil, apperrors.Unauthorized("authentication required")
	}

	query := `
		SELECT ke.id, ke.problem_id, ke.title, ke.description,
			ke.workaround, ke.kb_article_id, ke.status,
			ke.created_at, ke.updated_at
		FROM known_errors ke
		JOIN problems p ON p.id = ke.problem_id
		WHERE ke.problem_id = $1 AND p.tenant_id = $2
		ORDER BY ke.created_at DESC`

	rows, err := s.pool.Query(ctx, query, problemID, auth.TenantID)
	if err != nil {
		return nil, apperrors.Internal("failed to list known errors", err)
	}
	defer rows.Close()

	var errors []KnownError
	for rows.Next() {
		var ke KnownError
		if err := rows.Scan(
			&ke.ID, &ke.ProblemID, &ke.Title, &ke.Description,
			&ke.Workaround, &ke.KBArticleID, &ke.Status,
			&ke.CreatedAt, &ke.UpdatedAt,
		); err != nil {
			return nil, apperrors.Internal("failed to scan known error", err)
		}
		errors = append(errors, ke)
	}

	if err := rows.Err(); err != nil {
		return nil, apperrors.Internal("failed to iterate known errors", err)
	}

	if errors == nil {
		errors = []KnownError{}
	}

	return errors, nil
}

// UpdateKnownError updates an existing known error using COALESCE partial update.
func (s *ProblemService) UpdateKnownError(ctx context.Context, id uuid.UUID, req UpdateKnownErrorRequest) (KnownError, error) {
	auth := types.GetAuthContext(ctx)
	if auth == nil {
		return KnownError{}, apperrors.Unauthorized("authentication required")
	}

	// Verify the known error exists and belongs to the tenant.
	_, err := s.GetKnownError(ctx, id)
	if err != nil {
		return KnownError{}, err
	}

	now := time.Now().UTC()

	updateQuery := `
		UPDATE known_errors SET
			title = COALESCE($1, title),
			description = COALESCE($2, description),
			workaround = COALESCE($3, workaround),
			kb_article_id = COALESCE($4, kb_article_id),
			status = COALESCE($5, status),
			updated_at = $6
		WHERE id = $7
		RETURNING id, problem_id, title, description,
			workaround, kb_article_id, status,
			created_at, updated_at`

	var ke KnownError
	err = s.pool.QueryRow(ctx, updateQuery,
		req.Title, req.Description, req.Workaround,
		req.KBArticleID, req.Status,
		now, id,
	).Scan(
		&ke.ID, &ke.ProblemID, &ke.Title, &ke.Description,
		&ke.Workaround, &ke.KBArticleID, &ke.Status,
		&ke.CreatedAt, &ke.UpdatedAt,
	)
	if err != nil {
		return KnownError{}, apperrors.Internal("failed to update known error", err)
	}

	// Log audit event.
	changes, _ := json.Marshal(req)
	if auditErr := s.auditSvc.Log(ctx, audit.AuditEntry{
		TenantID:   auth.TenantID,
		ActorID:    auth.UserID,
		Action:     "update:known_error",
		EntityType: "known_error",
		EntityID:   id,
		Changes:    changes,
	}); auditErr != nil {
		slog.ErrorContext(ctx, "failed to log audit event", "error", auditErr)
	}

	return ke, nil
}

// DeleteKnownError deletes a known error by ID.
func (s *ProblemService) DeleteKnownError(ctx context.Context, id uuid.UUID) error {
	auth := types.GetAuthContext(ctx)
	if auth == nil {
		return apperrors.Unauthorized("authentication required")
	}

	// Verify the known error belongs to the tenant before deleting.
	ke, err := s.GetKnownError(ctx, id)
	if err != nil {
		return err
	}

	query := `DELETE FROM known_errors WHERE id = $1`

	result, err := s.pool.Exec(ctx, query, id)
	if err != nil {
		return apperrors.Internal("failed to delete known error", err)
	}

	if result.RowsAffected() == 0 {
		return apperrors.NotFound("KnownError", id.String())
	}

	// Log audit event.
	if auditErr := s.auditSvc.Log(ctx, audit.AuditEntry{
		TenantID:   auth.TenantID,
		ActorID:    auth.UserID,
		Action:     "delete:known_error",
		EntityType: "known_error",
		EntityID:   ke.ID,
	}); auditErr != nil {
		slog.ErrorContext(ctx, "failed to log audit event", "error", auditErr)
	}

	return nil
}
