package itsm

import (
	"context"
	"encoding/json"
	"log/slog"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/nats-io/nats.go"

	"github.com/itd-cbn/itd-opms-api/internal/platform/audit"
	"github.com/itd-cbn/itd-opms-api/internal/platform/workflow"
	apperrors "github.com/itd-cbn/itd-opms-api/internal/shared/errors"
	"github.com/itd-cbn/itd-opms-api/internal/shared/types"
)

// ──────────────────────────────────────────────
// ProblemService
// ──────────────────────────────────────────────

// ProblemService handles business logic for problem management and known errors.
type ProblemService struct {
	pool     *pgxpool.Pool
	auditSvc *audit.AuditService
	js       nats.JetStreamContext
}

// NewProblemService creates a new ProblemService.
func NewProblemService(pool *pgxpool.Pool, auditSvc *audit.AuditService, js nats.JetStreamContext) *ProblemService {
	return &ProblemService{
		pool:     pool,
		auditSvc: auditSvc,
		js:       js,
	}
}

// ──────────────────────────────────────────────
// Problem column helpers
// ──────────────────────────────────────────────

// problemBaseColumns is used in RETURNING clauses (no JOINs available).
const problemBaseColumns = `id, tenant_id, problem_number, title, description,
	root_cause, status, linked_incident_ids, workaround,
	permanent_fix, linked_change_id, owner_id, assigned_group_id,
	created_at, updated_at`

// problemSelectColumns includes enrichment via LEFT JOINs.
const problemSelectColumns = `p.id, p.tenant_id, p.problem_number, p.title, p.description,
	p.root_cause, p.status, p.linked_incident_ids, p.workaround,
	p.permanent_fix, p.linked_change_id, p.owner_id, p.assigned_group_id,
	p.created_at, p.updated_at,
	ou.name AS assigned_group_name,
	owner.display_name AS owner_name`

const problemFromJoins = `FROM problems p
	LEFT JOIN org_units ou ON ou.id = p.assigned_group_id
	LEFT JOIN users owner ON owner.id = p.owner_id`

func scanProblemBase(row pgx.Row) (Problem, error) {
	var p Problem
	err := row.Scan(
		&p.ID, &p.TenantID, &p.ProblemNumber, &p.Title, &p.Description,
		&p.RootCause, &p.Status, &p.LinkedIncidentIDs, &p.Workaround,
		&p.PermanentFix, &p.LinkedChangeID, &p.OwnerID, &p.AssignedGroupID,
		&p.CreatedAt, &p.UpdatedAt,
	)
	return p, err
}

func scanProblemEnriched(row pgx.Row) (Problem, error) {
	var p Problem
	err := row.Scan(
		&p.ID, &p.TenantID, &p.ProblemNumber, &p.Title, &p.Description,
		&p.RootCause, &p.Status, &p.LinkedIncidentIDs, &p.Workaround,
		&p.PermanentFix, &p.LinkedChangeID, &p.OwnerID, &p.AssignedGroupID,
		&p.CreatedAt, &p.UpdatedAt,
		&p.AssignedGroupName, &p.OwnerName,
	)
	return p, err
}

// ──────────────────────────────────────────────
// Problems
// ──────────────────────────────────────────────

// CreateProblem creates a new problem record. The problem_number is auto-generated by a DB trigger.
func (s *ProblemService) CreateProblem(ctx context.Context, req CreateProblemRequest) (Problem, error) {
	auth := types.GetAuthContext(ctx)
	if auth == nil {
		return Problem{}, apperrors.Unauthorized("authentication required")
	}

	id := uuid.New()
	now := time.Now().UTC()

	query := `
		INSERT INTO problems (
			id, tenant_id, title, description,
			status, owner_id, assigned_group_id, created_at, updated_at
		) VALUES (
			$1, $2, $3, $4,
			$5, $6, $7, $8, $9
		)
		RETURNING ` + problemBaseColumns

	status := req.Status
	if status == "" {
		status = "logged"
	}

	p, err := scanProblemBase(s.pool.QueryRow(ctx, query,
		id, auth.TenantID, req.Title, req.Description,
		status, req.OwnerID, req.AssignedGroupID, now, now,
	))
	if err != nil {
		return Problem{}, apperrors.Internal("failed to create problem", err)
	}

	// Log audit event.
	changes, _ := json.Marshal(map[string]any{
		"title":  req.Title,
		"status": "open",
	})
	if auditErr := s.auditSvc.Log(ctx, audit.AuditEntry{
		TenantID:   auth.TenantID,
		ActorID:    auth.UserID,
		Action:     "create:problem",
		EntityType: "problem",
		EntityID:   id,
		Changes:    changes,
	}); auditErr != nil {
		slog.ErrorContext(ctx, "failed to log audit event", "error", auditErr)
	}

	return p, nil
}

// GetProblem retrieves a single problem by ID.
func (s *ProblemService) GetProblem(ctx context.Context, id uuid.UUID) (Problem, error) {
	auth := types.GetAuthContext(ctx)
	if auth == nil {
		return Problem{}, apperrors.Unauthorized("authentication required")
	}

	query := `SELECT ` + problemSelectColumns + ` ` + problemFromJoins + `
		WHERE p.id = $1 AND p.tenant_id = $2`

	p, err := scanProblemEnriched(s.pool.QueryRow(ctx, query, id, auth.TenantID))
	if err != nil {
		if err == pgx.ErrNoRows {
			return Problem{}, apperrors.NotFound("Problem", id.String())
		}
		return Problem{}, apperrors.Internal("failed to get problem", err)
	}

	return p, nil
}

// ListProblems returns a filtered, paginated list of problems.
func (s *ProblemService) ListProblems(ctx context.Context, status *string, assignedGroupID *uuid.UUID, limit, offset int) ([]Problem, int64, error) {
	auth := types.GetAuthContext(ctx)
	if auth == nil {
		return nil, 0, apperrors.Unauthorized("authentication required")
	}

	// Count total matching records.
	countQuery := `
		SELECT COUNT(*)
		FROM problems
		WHERE tenant_id = $1
			AND ($2::text IS NULL OR status = $2)
			AND ($3::uuid IS NULL OR assigned_group_id = $3)`

	var total int64
	err := s.pool.QueryRow(ctx, countQuery, auth.TenantID, status, assignedGroupID).Scan(&total)
	if err != nil {
		return nil, 0, apperrors.Internal("failed to count problems", err)
	}

	// Fetch paginated results with enrichment.
	dataQuery := `SELECT ` + problemSelectColumns + ` ` + problemFromJoins + `
		WHERE p.tenant_id = $1
			AND ($2::text IS NULL OR p.status = $2)
			AND ($3::uuid IS NULL OR p.assigned_group_id = $3)
		ORDER BY p.created_at DESC
		LIMIT $4 OFFSET $5`

	rows, err := s.pool.Query(ctx, dataQuery, auth.TenantID, status, assignedGroupID, limit, offset)
	if err != nil {
		return nil, 0, apperrors.Internal("failed to list problems", err)
	}
	defer rows.Close()

	var problems []Problem
	for rows.Next() {
		p, err := scanProblemEnriched(rows)
		if err != nil {
			return nil, 0, apperrors.Internal("failed to scan problem", err)
		}
		problems = append(problems, p)
	}

	if err := rows.Err(); err != nil {
		return nil, 0, apperrors.Internal("failed to iterate problems", err)
	}

	if problems == nil {
		problems = []Problem{}
	}

	return problems, total, nil
}

// UpdateProblem updates an existing problem using COALESCE partial update.
func (s *ProblemService) UpdateProblem(ctx context.Context, id uuid.UUID, req UpdateProblemRequest) (Problem, error) {
	auth := types.GetAuthContext(ctx)
	if auth == nil {
		return Problem{}, apperrors.Unauthorized("authentication required")
	}

	// Verify the problem exists and belongs to the tenant.
	_, err := s.GetProblem(ctx, id)
	if err != nil {
		return Problem{}, err
	}

	now := time.Now().UTC()

	// NOTE: status is intentionally excluded — use TransitionProblem instead.
	updateQuery := `
		UPDATE problems SET
			title = COALESCE($1, title),
			description = COALESCE($2, description),
			root_cause = COALESCE($3, root_cause),
			workaround = COALESCE($4, workaround),
			permanent_fix = COALESCE($5, permanent_fix),
			linked_change_id = COALESCE($6, linked_change_id),
			owner_id = COALESCE($7, owner_id),
			assigned_group_id = COALESCE($8, assigned_group_id),
			updated_at = $9
		WHERE id = $10 AND tenant_id = $11
		RETURNING ` + problemBaseColumns

	p, err := scanProblemBase(s.pool.QueryRow(ctx, updateQuery,
		req.Title, req.Description, req.RootCause,
		req.Workaround, req.PermanentFix,
		req.LinkedChangeID, req.OwnerID, req.AssignedGroupID,
		now, id, auth.TenantID,
	))
	if err != nil {
		return Problem{}, apperrors.Internal("failed to update problem", err)
	}

	// Log audit event.
	changes, _ := json.Marshal(req)
	if auditErr := s.auditSvc.Log(ctx, audit.AuditEntry{
		TenantID:   auth.TenantID,
		ActorID:    auth.UserID,
		Action:     "update:problem",
		EntityType: "problem",
		EntityID:   id,
		Changes:    changes,
	}); auditErr != nil {
		slog.ErrorContext(ctx, "failed to log audit event", "error", auditErr)
	}

	return p, nil
}

// DeleteProblem deletes a problem by ID.
func (s *ProblemService) DeleteProblem(ctx context.Context, id uuid.UUID) error {
	auth := types.GetAuthContext(ctx)
	if auth == nil {
		return apperrors.Unauthorized("authentication required")
	}

	query := `DELETE FROM problems WHERE id = $1 AND tenant_id = $2`

	result, err := s.pool.Exec(ctx, query, id, auth.TenantID)
	if err != nil {
		return apperrors.Internal("failed to delete problem", err)
	}

	if result.RowsAffected() == 0 {
		return apperrors.NotFound("Problem", id.String())
	}

	// Log audit event.
	if auditErr := s.auditSvc.Log(ctx, audit.AuditEntry{
		TenantID:   auth.TenantID,
		ActorID:    auth.UserID,
		Action:     "delete:problem",
		EntityType: "problem",
		EntityID:   id,
	}); auditErr != nil {
		slog.ErrorContext(ctx, "failed to log audit event", "error", auditErr)
	}

	return nil
}

// LinkIncident appends an incident ID to the problem's linked_incident_ids array.
func (s *ProblemService) LinkIncident(ctx context.Context, problemID, incidentID uuid.UUID) error {
	auth := types.GetAuthContext(ctx)
	if auth == nil {
		return apperrors.Unauthorized("authentication required")
	}

	query := `
		UPDATE problems SET
			linked_incident_ids = array_append(linked_incident_ids, $1),
			updated_at = $2
		WHERE id = $3 AND tenant_id = $4`

	now := time.Now().UTC()
	result, err := s.pool.Exec(ctx, query, incidentID, now, problemID, auth.TenantID)
	if err != nil {
		return apperrors.Internal("failed to link incident to problem", err)
	}

	if result.RowsAffected() == 0 {
		return apperrors.NotFound("Problem", problemID.String())
	}

	// Log audit event.
	changes, _ := json.Marshal(map[string]any{
		"linked_incident_id": incidentID,
	})
	if auditErr := s.auditSvc.Log(ctx, audit.AuditEntry{
		TenantID:   auth.TenantID,
		ActorID:    auth.UserID,
		Action:     "link_incident:problem",
		EntityType: "problem",
		EntityID:   problemID,
		Changes:    changes,
	}); auditErr != nil {
		slog.ErrorContext(ctx, "failed to log audit event", "error", auditErr)
	}

	return nil
}

// ──────────────────────────────────────────────
// Problem Status Transitions
// ──────────────────────────────────────────────

// TransitionProblem validates and performs a status transition on a problem.
func (s *ProblemService) TransitionProblem(ctx context.Context, id uuid.UUID, req TransitionProblemRequest) (Problem, error) {
	auth := types.GetAuthContext(ctx)
	if auth == nil {
		return Problem{}, apperrors.Unauthorized("authentication required")
	}

	existing, err := s.GetProblem(ctx, id)
	if err != nil {
		return Problem{}, err
	}

	// Validate transition against workflow state machine.
	if err := workflow.ProblemStateMachine.Validate(existing.Status, req.TargetStatus); err != nil {
		return Problem{}, apperrors.BadRequest(err.Error())
	}

	now := time.Now().UTC()

	query := `
		UPDATE problems SET
			status = $1,
			updated_at = $2
		WHERE id = $3 AND tenant_id = $4
		RETURNING ` + problemBaseColumns

	p, err := scanProblemBase(s.pool.QueryRow(ctx, query, req.TargetStatus, now, id, auth.TenantID))
	if err != nil {
		return Problem{}, apperrors.Internal("failed to transition problem status", err)
	}

	// Auto-create known_error record when transitioning to known_error.
	if req.TargetStatus == ProblemStatusKnownError {
		var keCount int
		_ = s.pool.QueryRow(ctx, `SELECT COUNT(*) FROM known_errors WHERE problem_id = $1`, id).Scan(&keCount)
		if keCount == 0 {
			keID := uuid.New()
			keTitle := "Known Error — " + p.Title
			_, keErr := s.pool.Exec(ctx, `
				INSERT INTO known_errors (id, problem_id, title, description, workaround, status, created_at, updated_at)
				VALUES ($1, $2, $3, $4, $5, 'active', $6, $7)`,
				keID, id, keTitle, p.RootCause, p.Workaround, now, now,
			)
			if keErr != nil {
				slog.ErrorContext(ctx, "failed to auto-create known error", "error", keErr)
			} else {
				slog.InfoContext(ctx, "auto-created known error for problem", "problem_id", id, "known_error_id", keID)
			}
		}
	}

	// Log audit event.
	changes, _ := json.Marshal(map[string]any{
		"previous_status": existing.Status,
		"new_status":      req.TargetStatus,
		"comment":         req.Comment,
	})
	if auditErr := s.auditSvc.Log(ctx, audit.AuditEntry{
		TenantID:   auth.TenantID,
		ActorID:    auth.UserID,
		Action:     "transition:problem",
		EntityType: "problem",
		EntityID:   id,
		Changes:    changes,
	}); auditErr != nil {
		slog.ErrorContext(ctx, "failed to log audit event", "error", auditErr)
	}

	// Publish NATS event.
	if s.js != nil {
		eventData, _ := json.Marshal(map[string]any{
			"problemId":      id,
			"problemNumber":  p.ProblemNumber,
			"title":          p.Title,
			"previousStatus": existing.Status,
			"newStatus":      req.TargetStatus,
			"comment":        req.Comment,
			"actorId":         auth.UserID,
			"ownerId":         p.OwnerID,
			"assignedGroupId": p.AssignedGroupID,
		})
		payload, _ := json.Marshal(map[string]any{
			"type":       "itsm.problem.transitioned",
			"tenantId":   auth.TenantID,
			"actorId":    auth.UserID,
			"entityType": "problem",
			"entityId":   id,
			"data":       json.RawMessage(eventData),
		})
		if _, pubErr := s.js.Publish("notify.itsm.problem.transitioned", payload); pubErr != nil {
			slog.ErrorContext(ctx, "failed to publish problem transition event", "error", pubErr)
		}
	}

	return p, nil
}

// ──────────────────────────────────────────────
// Known Errors
// ──────────────────────────────────────────────

// CreateKnownError creates a new known error record linked to a problem.
func (s *ProblemService) CreateKnownError(ctx context.Context, req CreateKnownErrorRequest) (KnownError, error) {
	auth := types.GetAuthContext(ctx)
	if auth == nil {
		return KnownError{}, apperrors.Unauthorized("authentication required")
	}

	id := uuid.New()
	now := time.Now().UTC()

	query := `
		INSERT INTO known_errors (
			id, problem_id, title, description,
			workaround, kb_article_id, status,
			created_at, updated_at
		) VALUES (
			$1, $2, $3, $4,
			$5, $6, 'active',
			$7, $8
		)
		RETURNING id, problem_id, title, description,
			workaround, kb_article_id, status,
			created_at, updated_at`

	var ke KnownError
	err := s.pool.QueryRow(ctx, query,
		id, req.ProblemID, req.Title, req.Description,
		req.Workaround, req.KBArticleID,
		now, now,
	).Scan(
		&ke.ID, &ke.ProblemID, &ke.Title, &ke.Description,
		&ke.Workaround, &ke.KBArticleID, &ke.Status,
		&ke.CreatedAt, &ke.UpdatedAt,
	)
	if err != nil {
		return KnownError{}, apperrors.Internal("failed to create known error", err)
	}

	// Log audit event.
	changes, _ := json.Marshal(map[string]any{
		"title":      req.Title,
		"problem_id": req.ProblemID,
	})
	if auditErr := s.auditSvc.Log(ctx, audit.AuditEntry{
		TenantID:   auth.TenantID,
		ActorID:    auth.UserID,
		Action:     "create:known_error",
		EntityType: "known_error",
		EntityID:   id,
		Changes:    changes,
	}); auditErr != nil {
		slog.ErrorContext(ctx, "failed to log audit event", "error", auditErr)
	}

	return ke, nil
}

// GetKnownError retrieves a single known error by ID.
func (s *ProblemService) GetKnownError(ctx context.Context, id uuid.UUID) (KnownError, error) {
	auth := types.GetAuthContext(ctx)
	if auth == nil {
		return KnownError{}, apperrors.Unauthorized("authentication required")
	}

	query := `
		SELECT ke.id, ke.problem_id, ke.title, ke.description,
			ke.workaround, ke.kb_article_id, ke.status,
			ke.created_at, ke.updated_at
		FROM known_errors ke
		JOIN problems p ON p.id = ke.problem_id
		WHERE ke.id = $1 AND p.tenant_id = $2`

	var ke KnownError
	err := s.pool.QueryRow(ctx, query, id, auth.TenantID).Scan(
		&ke.ID, &ke.ProblemID, &ke.Title, &ke.Description,
		&ke.Workaround, &ke.KBArticleID, &ke.Status,
		&ke.CreatedAt, &ke.UpdatedAt,
	)
	if err != nil {
		if err == pgx.ErrNoRows {
			return KnownError{}, apperrors.NotFound("KnownError", id.String())
		}
		return KnownError{}, apperrors.Internal("failed to get known error", err)
	}

	return ke, nil
}

// ListKnownErrors returns all known errors for a given problem.
func (s *ProblemService) ListKnownErrors(ctx context.Context, problemID uuid.UUID) ([]KnownError, error) {
	auth := types.GetAuthContext(ctx)
	if auth == nil {
		return nil, apperrors.Unauthorized("authentication required")
	}

	query := `
		SELECT ke.id, ke.problem_id, ke.title, ke.description,
			ke.workaround, ke.kb_article_id, ke.status,
			ke.created_at, ke.updated_at
		FROM known_errors ke
		JOIN problems p ON p.id = ke.problem_id
		WHERE ke.problem_id = $1 AND p.tenant_id = $2
		ORDER BY ke.created_at DESC`

	rows, err := s.pool.Query(ctx, query, problemID, auth.TenantID)
	if err != nil {
		return nil, apperrors.Internal("failed to list known errors", err)
	}
	defer rows.Close()

	var errors []KnownError
	for rows.Next() {
		var ke KnownError
		if err := rows.Scan(
			&ke.ID, &ke.ProblemID, &ke.Title, &ke.Description,
			&ke.Workaround, &ke.KBArticleID, &ke.Status,
			&ke.CreatedAt, &ke.UpdatedAt,
		); err != nil {
			return nil, apperrors.Internal("failed to scan known error", err)
		}
		errors = append(errors, ke)
	}

	if err := rows.Err(); err != nil {
		return nil, apperrors.Internal("failed to iterate known errors", err)
	}

	if errors == nil {
		errors = []KnownError{}
	}

	return errors, nil
}

// UpdateKnownError updates an existing known error using COALESCE partial update.
func (s *ProblemService) UpdateKnownError(ctx context.Context, id uuid.UUID, req UpdateKnownErrorRequest) (KnownError, error) {
	auth := types.GetAuthContext(ctx)
	if auth == nil {
		return KnownError{}, apperrors.Unauthorized("authentication required")
	}

	// Verify the known error exists and belongs to the tenant.
	_, err := s.GetKnownError(ctx, id)
	if err != nil {
		return KnownError{}, err
	}

	now := time.Now().UTC()

	updateQuery := `
		UPDATE known_errors SET
			title = COALESCE($1, title),
			description = COALESCE($2, description),
			workaround = COALESCE($3, workaround),
			kb_article_id = COALESCE($4, kb_article_id),
			status = COALESCE($5, status),
			updated_at = $6
		WHERE id = $7
		RETURNING id, problem_id, title, description,
			workaround, kb_article_id, status,
			created_at, updated_at`

	var ke KnownError
	err = s.pool.QueryRow(ctx, updateQuery,
		req.Title, req.Description, req.Workaround,
		req.KBArticleID, req.Status,
		now, id,
	).Scan(
		&ke.ID, &ke.ProblemID, &ke.Title, &ke.Description,
		&ke.Workaround, &ke.KBArticleID, &ke.Status,
		&ke.CreatedAt, &ke.UpdatedAt,
	)
	if err != nil {
		return KnownError{}, apperrors.Internal("failed to update known error", err)
	}

	// Log audit event.
	changes, _ := json.Marshal(req)
	if auditErr := s.auditSvc.Log(ctx, audit.AuditEntry{
		TenantID:   auth.TenantID,
		ActorID:    auth.UserID,
		Action:     "update:known_error",
		EntityType: "known_error",
		EntityID:   id,
		Changes:    changes,
	}); auditErr != nil {
		slog.ErrorContext(ctx, "failed to log audit event", "error", auditErr)
	}

	return ke, nil
}

// DeleteKnownError deletes a known error by ID.
func (s *ProblemService) DeleteKnownError(ctx context.Context, id uuid.UUID) error {
	auth := types.GetAuthContext(ctx)
	if auth == nil {
		return apperrors.Unauthorized("authentication required")
	}

	// Verify the known error belongs to the tenant before deleting.
	ke, err := s.GetKnownError(ctx, id)
	if err != nil {
		return err
	}

	query := `DELETE FROM known_errors WHERE id = $1`

	result, err := s.pool.Exec(ctx, query, id)
	if err != nil {
		return apperrors.Internal("failed to delete known error", err)
	}

	if result.RowsAffected() == 0 {
		return apperrors.NotFound("KnownError", id.String())
	}

	// Log audit event.
	if auditErr := s.auditSvc.Log(ctx, audit.AuditEntry{
		TenantID:   auth.TenantID,
		ActorID:    auth.UserID,
		Action:     "delete:known_error",
		EntityType: "known_error",
		EntityID:   ke.ID,
	}); auditErr != nil {
		slog.ErrorContext(ctx, "failed to log audit event", "error", auditErr)
	}

	return nil
}
